kairos/urls.py
""" project urls registration """
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import RedirectView

from mbr_announcements.views import AnnouncementsListView
from mbr_meeting_plugin.views import MemberMeetingAddView
from mbr_messages.views import MemberMessageListView
from kairos.views import (
    MemberEmailSignupView, MembersListView, MemberLoginView, signup_email_confirm, signup_paid_confirm)


admin.autodiscover()

favicon_url = staticfiles_storage.url("favicon.ico")

urlpatterns = [
    path('sitemap.xml', sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
    path('favicon.ico', RedirectView.as_view(url=favicon_url)),
]
urlpatterns += i18n_patterns(
    path('accounts/login/', MemberLoginView.as_view(), name='login'),               # overwrite login in auth.urls.py
    path('accounts/logout/', LogoutView.as_view(next_page="/"), name='logout'),     # overwrite logout in auth.urls.py
    # not used because gets redirected to the previous page/referer in kairos/templates/registration/login.html
    path('accounts/profile/', RedirectView.as_view(url="/")),                       # redirect to home after login
    path('accounts/', include('django.contrib.auth.urls')),

    path('signup/member/', MemberEmailSignupView.as_view(), name='signup-member'),  # CMS-page reverse name mbr-signup
    path('signup/confirm/<str:key>/<str:token>/', signup_email_confirm, name='signup-confirm'),
    path('signup/paid/<str:keys>/<str:token>/', signup_paid_confirm, name='signup-paid'),

    path("admin/", admin.site.urls),

    # all url kwargs are slugified with exception to 'announcement-add' which is using capitalized category/action names
    path('announcements/list/', AnnouncementsListView.as_view(), name='announcements-list'),
    path('announcements/add/<str:cat>/<str:act>', AnnouncementsListView.as_view(), name='announcement-add'),
    path('announcements/edit/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-edit'),
    path('announcements/update/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-update'),
    path('announcements/delete/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-delete'),
    path('announcements/show/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-show'),

    path('meetings/update/', MemberMeetingAddView.as_view(), name='meetings-update'),

    path('messages/list/', MemberMessageListView.as_view(), name='messages-list'),
    path('messages/add/', MemberMessageListView.as_view(), name='message-add'),
    path('messages/edit/<int:id>', MemberMessageListView.as_view(), name='message-edit'),
    path('messages/update/<int:id>', MemberMessageListView.as_view(), name='message-update'),
    path('messages/delete/<int:id>', MemberMessageListView.as_view(), name='message-delete'),
    path('messages/show/<int:id>', MemberMessageListView.as_view(), name='message-show'),

    path('members/list/', MembersListView.as_view(), name='members-list'),

    path('', include('cms.urls')),
)

if settings.DEBUG:  # only needed when using runserver
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

mbr_messages/models.py
""" member messages app models """
from django.conf import settings
from django.db import models

from kairos.utils import member_full_name


class MemberMessage(models.Model):
    """ member messages model """
    mm_author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mm_text = models.TextField()
    mm_public = models.BooleanField()
    mm_expired = models.DateField(null=True, blank=True)
    mm_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # noinspection PyUnresolvedReferences
        return (f"{self.__class__.__name__}@{member_full_name(self.mm_author)}" +
                (f"->{self.mm_expired}" if self.mm_expired else "") +
                (" (public)" if self.mm_public else "") +
                f":{self.mm_text}")

mbr_messages/views.py
""" member messages views """
import datetime
import re

from urllib.parse import urlparse

from cms.utils.permissions import get_current_user
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import ListView

from ae.django_utils import set_url_part

from kairos.utils import send_mbr_notif
from .models import MemberMessage


MSG_ADD_MARKER = "EmptyMemberMessage"
MSG_ANCHOR_ID_PREFIX = "MMsgAIdP"

MOBILE_AGENT_RE = re.compile(r".*(iphone|mobile|androidtouch)", re.IGNORECASE)


def check_change_notification(old_public: bool, old_expired: datetime.date, old_text: str,
                              new_public: bool, new_expired: datetime.date, new_text: str,
                              author: User, url: str):
    """ check for changes and if yes then send notifications to receivers.

    :param old_public:          old publication status of message.
    :param old_expired:         old message expiry date.
    :param old_text:            old message text.
    :param new_public:          new publication status.
    :param new_expired:         new expire date.
    :param new_text:            new message text.
    :param author:              message author user record.
    :param url:                 absolute url to show the changed message on the website.
    """
    added = MSG_ADD_MARKER in old_text
    changes = []
    if added:
        item = _("public message") if new_public else _("private message")
        if new_expired:
            item += " " + _("expiring {new_expired}").format(new_expired=new_expired)
        changes.append(new_text)
    else:
        item = _("message")
        prefix = "- "

        if old_public != new_public:
            changes.append(prefix + (_("made public") if new_public else _("revoked publication")))

        if old_expired != new_expired:
            if not old_expired:
                changes.append(prefix + _("added expiry date {new_expired}").format(new_expired=new_expired))
            elif not new_expired:
                changes.append(prefix + _("removed expiry date {old_expired}").format(old_expired=old_expired))
            else:
                changes.append(prefix + _("changed expiry date from {old_expired} to {new_expired}").format(
                    old_expired=old_expired, new_expired=new_expired))

        if old_text != new_text:
            changes.append(new_text)

    if changes:
        send_mbr_notif('added' if added else 'updated', changes, item, author, url)


def extend_context(context, request, **kwargs):
    """ extend context for view and plugin (to avoid redundancies) """
    context['MSG_ADD_MARKER'] = MSG_ADD_MARKER
    context['MSG_ANCHOR_ID_PREFIX'] = MSG_ANCHOR_ID_PREFIX
    context['is_mobile'] = MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT'])
    context['url_kwargs'] = kwargs


def get_queryset():
    """ get queryset of all objects for view and plugin (to avoid redundancies). """
    obj_list = MemberMessage.objects
    if not get_current_user().is_authenticated:
        obj_list = obj_list.filter(mm_public=True)
    return obj_list.order_by("-mm_created")


class MemberMessageListView(ListView):
    """ member messages list view """
    model = MemberMessage

    def get_context_data(self, **kwargs):
        """ context data """
        context = super().get_context_data(**kwargs)
        extend_context(context, self.request, **self.kwargs)
        return context

    def get_queryset(self):
        """ filter by currently selected language and order by category-name, action and newest changes first. """
        return get_queryset()

    def post(self, request, *args, **kwargs):
        """ handle member message edit. """
        mm_id: int = kwargs.get('id')
        if not mm_id:   # action == 'add'
            mm_author = get_current_user()
            row = MemberMessage.objects.create(
                mm_author=mm_author,
                mm_text=MSG_ADD_MARKER,
                mm_public=False,
            )
            mm_id = row.pk
            url = reverse('message-edit', kwargs={'id': mm_id})

        else:
            if request.path.split("/")[-2] == 'delete':
                rec = MemberMessage.objects.get(id=mm_id)
                pre_rec = self.get_queryset().filter(mm_created__lt=rec.mm_created).first()
                if pre_rec:
                    mm_id = pre_rec.pk
                    url = reverse('message-show', kwargs={'id': mm_id})
                else:
                    mm_id = 0
                    url = reverse('messages-list')
                if MSG_ADD_MARKER not in (txt := rec.mm_text):
                    send_mbr_notif('deleted', ([f"- {rec.mm_expired}"] if rec.mm_expired else []) + [txt],
                                   _("public message") if rec.mm_public else _("private message"), rec.mm_author)
                rec.delete()

            else:   # == 'update'
                rec = MemberMessage.objects.get(id=mm_id)
                old_public, old_expired, old_text, author = rec.mm_public, rec.mm_expired, rec.mm_text, rec.mm_author
                new_public, new_expired, new_text = (request.POST.get('mm_public') == 'on',
                                                     request.POST['mm_expired'] or None,
                                                     request.POST['mm_text'].strip())

                rec.mm_public, rec.mm_expired, rec.mm_text = new_public, new_expired, new_text
                rec.save()
                url = reverse('message-show', kwargs={'id': mm_id})

                check_change_notification(
                    old_public, old_expired, old_text,
                    new_public, new_expired, new_text,
                    author, set_url_part(request.build_absolute_uri(url), MSG_ANCHOR_ID_PREFIX + str(mm_id)))

        url = set_url_part(url, MSG_ANCHOR_ID_PREFIX + str(mm_id), urlparse(request.META.get('HTTP_REFERER')).query)

        return HttpResponseRedirect(url)

mbr_messages/templates/mbr_messages/membermessage_edit.html
{% load i18n kairos_tags %}

<div class="row mb-3 px-2 py-3 border border-info rounded-lg shadow">
    <form class="w-100">
        {% csrf_token %}
        <div class="row form-group">
            <div class="col-12 col-lg-2">
                <span class="ml-3" title="{{ msg.mm_author.last_name }}">{% full_name msg.mm_author %}</span>
            </div>
            <div class="col-12 col-lg-1 mx-1">
                <label for="is_public"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "is published" %}
                </label>
                <input id="is_public" type="checkbox" name="mm_public"{% if msg.mm_public %} checked{% endif %}
                       class="form-control"
                       title="{% translate "check to show this message publicly to any visitor of this website" %}">
            </div>
            <div class="col-12 col-lg-2 mx-1">
                <label for="expired_date"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "expire date" %}
                </label>
                <input id="expired_date" type="date" name="mm_expired" value="{{ msg.mm_expired|date:"c" }}"
                       min="{% now 'Y-m-d' %}"
                       class="form-control"
                       title="{% translate "enter the date until this message will be visible in the website news" %}">
            </div>
            <div class="col-12 col-lg-6 mx-1">
                <label for="message_text"
                       class="col-form-label font-italic font-weight-lighter" style="font-size: 81%">
                    {% translate "Text" %}
                </label>
                <!--suppress HtmlFormInputWithoutLabel -->
                <textarea id="message_text" name="mm_text" required style="min-width: 100%"
                          class="form-control text-area-auto-height"
                          title="{% translate "text of this member message" %}"
                          placeholder="{% translate "(enter new member message text)" %}"
                >{% if MSG_ADD_MARKER not in msg.mm_text %}{{ msg.mm_text }}{% endif %}</textarea>
            </div>
        </div>
        <div class="row pt-1">
            <div class="col-3 ml-1 ml-lg-5">
            {% if perms.mbr_messages.delete_membermessage %}
                <input class="btn btn-outline-info btn-sm" type="submit" value="{% translate "Delete" %}"
                       formaction="{% url 'message-delete' msg.pk %}" formmethod="post"
                       title="{% translate "delete this member message" %}">
            {% endif %}
            </div>
            <div class="col-8">
                <input class="btn btn-outline-info btn-sm w-100" type="submit" value="{% translate "Save" %}"
                       formaction="{% url 'message-update' msg.pk %}#{{ MSG_ANCHOR_ID_PREFIX }}{{ msg.pk }}"
                       formmethod="post"
                       title="{% translate "save any changes done to this member message" %}">
            </div>
        </div>
    </form>
</div>

mbr_messages/templates/mbr_messages/membermessage_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% translate "Messages" %} - {% translate "KairosBrandName" %}{% endblock %}

{% block content %}
    {% include "../membermessage_plugin.html" %}
{% endblock %}