kairos/urls.py
""" project urls registration """
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import RedirectView

from mbr_announcements.views import AnnouncementsListView
from mbr_meeting_plugin.views import MemberMeetingAddView
from mbr_messages.views import MemberMessageListView
from kairos.views import (
    MemberEmailSignupView, MembersListView, MemberLoginView, signup_email_confirm, signup_paid_confirm)


admin.autodiscover()

favicon_url = staticfiles_storage.url("favicon.ico")

urlpatterns = [
    path('sitemap.xml', sitemap, {"sitemaps": {"cmspages": CMSSitemap}}),
    path('favicon.ico', RedirectView.as_view(url=favicon_url)),
]
urlpatterns += i18n_patterns(
    path('accounts/login/', MemberLoginView.as_view(), name='login'),               # overwrite login in auth.urls.py
    path('accounts/logout/', LogoutView.as_view(next_page="/"), name='logout'),     # overwrite logout in auth.urls.py
    # not used because gets redirected to the previous page/referer in kairos/templates/registration/login.html
    path('accounts/profile/', RedirectView.as_view(url="/")),                       # redirect to home after login
    path('accounts/', include('django.contrib.auth.urls')),

    path('signup/member/', MemberEmailSignupView.as_view(), name='signup-member'),  # CMS-page reverse name mbr-signup
    path('signup/confirm/<str:key>/<str:token>/', signup_email_confirm, name='signup-confirm'),
    path('signup/paid/<str:keys>/<str:token>/', signup_paid_confirm, name='signup-paid'),

    path("admin/", admin.site.urls),

    # all url kwargs are slugified with exception to 'announcement-add' which is using capitalized category/action names
    path('announcements/list/', AnnouncementsListView.as_view(), name='announcements-list'),
    path('announcements/add/<str:cat>/<str:act>', AnnouncementsListView.as_view(), name='announcement-add'),
    path('announcements/edit/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-edit'),
    path('announcements/update/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-update'),
    path('announcements/delete/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-delete'),
    path('announcements/show/<str:cat>/<int:id>', AnnouncementsListView.as_view(), name='announcement-show'),

    path('meetings/update/', MemberMeetingAddView.as_view(), name='meetings-update'),

    path('messages/list/', MemberMessageListView.as_view(), name='messages-list'),
    path('messages/add/', MemberMessageListView.as_view(), name='message-add'),
    path('messages/edit/<int:id>', MemberMessageListView.as_view(), name='message-edit'),
    path('messages/update/<int:id>', MemberMessageListView.as_view(), name='message-update'),
    path('messages/delete/<int:id>', MemberMessageListView.as_view(), name='message-delete'),
    path('messages/show/<int:id>', MemberMessageListView.as_view(), name='message-show'),

    path('members/list/', MembersListView.as_view(), name='members-list'),

    path('', include('cms.urls')),
)

if settings.DEBUG:  # only needed when using runserver
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

mbr_meeting_plugin/models.py
""" member meetings model """
from django.conf import settings
from django.db import models

from kairos.utils import member_full_name


class MemberMeeting(models.Model):
    """ member meetings model """
    mt_author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mt_language = models.CharField(max_length=3, choices=settings.LANGUAGES)
    mt_text = models.TextField()
    mt_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # noinspection PyUnresolvedReferences
        return (f"{self.__class__.__name__}-{self.mt_created}={self.mt_language}"
                f"@{member_full_name(self.mt_author)}"
                f":{self.mt_text}")

mbr_meeting_plugin/views.py
""" view to add a new member meeting text. """
from cms.utils.permissions import get_current_user
from django.conf import settings
from django.shortcuts import redirect
from django.utils.html import strip_tags
from django.utils.translation import override
from django.views import View

from ae.django_utils import requested_language

from mbr_meeting_plugin.models import MemberMeeting
from kairos.utils import send_mbr_notif


MBR_MEET_ANCHOR_ID_PREFIX = 'MMeetAIdP'


class MemberMeetingAddView(View):
    """ add new member meeting with text block, language, author, created date. """
    @staticmethod
    def post(request, *args, **kwargs):
        """ form post to add new member meeting text into the database. """
        updated_languages = []
        for lang, _lang_name in settings.LANGUAGES:
            updated_text = request.POST.get(lang + '_text')
            if updated_text != request.POST.get(lang + '_old_text'):
                MemberMeeting.objects.create(
                    mt_author=get_current_user(),
                    mt_language=lang,
                    mt_text=updated_text,
                )
                updated_languages.append(lang)

            if request.POST.get(lang + '_notify'):
                with override(lang):
                    send_mbr_notif('meeting', [strip_tags(updated_text)])   # strip tags for Telegram

        return redirect(request.META.get('HTTP_REFERER', '/') + '#' + MBR_MEET_ANCHOR_ID_PREFIX +
                        (updated_languages and updated_languages[0] or requested_language()))

mbr_meeting_plugin/templates/membermeetings_plugin.html
{% load i18n kairos_tags %}

{% if perms.mbr_meeting_plugin.add_membermeeting %}
    <form class="w-100">
        {% csrf_token %}
        {% for lang, text in mt_texts.items %}
            <a id="{{ MBR_MEET_ANCHOR_ID_PREFIX }}{{ lang }}"></a>
            <input type="hidden" name="{{ lang }}_old_text" value="{{ text }}">
            <div class="row form-group mb-0">
                <label for="txt_edit{{ lang }}" class="col-form-label">
                    <span class="{% flag_icon lang %}"></span>
                </label>
                <textarea id="txt_edit{{ lang }}" name="{{ lang }}_text" required style="min-width: 100%"
                          class="form-control text-area-auto-height"
                          title="{% translate "Text" %}"
                >{{ text }}</textarea>
            </div>
            <div class="row mt-0">
                <div class="offset-1 col-9 ml-1 ml-lg-5">
                    <input id="{{ lang }}_notify" type="checkbox" name="{{ lang }}_notify">
                    <label for="{{ lang }}_notify" class="col-form-label">
                        {% language lang %}{% translate "Notify members" %}{% endlanguage %}
                    </label>
                </div>
            </div>
        {% endfor %}
        <div class="offset-3 col-8">
            <input class="btn btn-outline-info btn-sm w-100 mt-0" type="submit"
                   value="{% translate "Update and/or Notify" %}"
                   formaction="{% url 'meetings-update' %}" formmethod="post">
        </div>
    </form>
{% else %}
    <div style="white-space: pre-wrap">{{ mt_lang_text|safe|linebreaks }}</div>
{% endif %}